/*
** Machine.cpp for Machine in /home/mathon_j/rendu/rushhell/rushhell/purgatory/etape1
** 
** Made by Jérémy MATHON
** Login   <mathon_j@mathonj>
** 
** Started on  Sat Nov 28 18:51:32 2015 Jérémy MATHON
** Last update Sat Nov 28 18:55:55 2015 Jérémy MATHON
*/

#include "Machine.hpp"

eState		gStateTable[STATE_MAX][EDGE_MAX] =
  { 
    {S1, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR},
    {STATE_ERROR, S2, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR},
    {STATE_ERROR, STATE_ERROR, S3, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR},
    {STATE_ERROR, STATE_ERROR, STATE_ERROR, S4, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR},
    {STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, S5, STATE_ERROR, STATE_ERROR, STATE_ERROR},
    {STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, S6, STATE_ERROR, STATE_ERROR},
    {STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, S7, STATE_ERROR},
    {STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR, STATE_ERROR}
  };

eAction		gActionTable[STATE_MAX][EDGE_MAX] =
  { 
    {MA, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR},
    {ACTION_ERROR, MA, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR},
    {ACTION_ERROR, ACTION_ERROR, MA, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR},
    {ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, MA, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR},
    {ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, MA, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR},
    {ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, MA, ACTION_ERROR, ACTION_ERROR},
    {ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, ACTION_ERROR, MA, ACTION_ERROR},
    {HR, HR, HR, HR, HR, HR, HR, HR}
  };

